version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: flipkart-pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: flipkartdb
      POSTGRES_USER: flipkart
      POSTGRES_PASSWORD: flipkart123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  pgdata:
